version: '3'

services:
  jukebox-client:
    container_name: jukebox-client
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
    command: yarn start
    volumes:
      - ./frontend:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_WS_URL=localhost
      - REACT_APP_WS_PORT=8080
      - REACT_APP_CLIENT_ID=${CLIENT_ID}
      - GOOGLE_AUTH_DOMAIN=${GOOGLE_AUTH_DOMAIN}
    tty: true
  jukebox-api:
    container_name: jukebox-api
    build:
      context: ./backend
      args:
        - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: yarn start
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - NODE_ENV=development
      - PORT=8080
      - IS_ALIVE_TIMEOUT=30000
      - WS_MOPIDY_URL=${WS_MOPIDY_URL}
      - WS_MOPIDY_PORT=${WS_MOPIDY_PORT}
      - MONGODB_URL=mongodb://mongodb:27017/jb-dev
      - SPOTIFY_ID=${SPOTIFY_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SPOTIFY_NEW_TRACKS_ADDED_LIMIT=3
      - CLIENT_ID=${CLIENT_ID}
      - EXPLICIT_CONTENT=${EXPLICIT_CONTENT}
      - GOOGLE_AUTH_DOMAIN=${GOOGLE_AUTH_DOMAIN}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=jb-dev
    volumes:
      - ./mongodb-data/db:/data/db:delegated
    ports:
      - 27017:27017
