export default {
  ADD_CURRENT_TRACK: 'actionAddCurrentTrack',
  ADD_TRACKS: 'actionAddTracks',
  CONNECT: 'actionConnect',
  CONNECTING: 'actionConnecting',
  CONNECTED: 'actionConnected',
  DISCONNECT: 'actionDisconnect',
  DISCONNECTED: 'actionDisconnected',
  DROP_TYPES: ['__NATIVE_URL__'],
  RESOLVE_IMAGE: 'actionResolveImage',
  SEND: 'actionSend',
  IMAGE_REQUEST: 'actionRequestImage',
  STORE_TOKEN: 'actionStoreToken',
  CLEAR_STORE_TOKEN: 'actionClearStoreToken',
  UPDATE_VOLUME: 'actionUpdateVolume',
  UPDATE_PLAYBACK_STATE: 'actionPlaybackState',
  UPDATE_PROGRESS_TIMER: 'actionUpdateProgressTimer',
  MOPIDY_CONNECTED: 'actionMopidyConnected',
  MOPIDY_DISCONNECTED: 'actionMopidyDisconnected'
}
