export default {
  ADD_CURRENT_TRACK: 'actionAddCurrentTrack',
  ADD_TRACKS: 'actionAddTracks',
  CONNECT: 'actionConnect',
  CONNECTING: 'actionConnecting',
  CONNECTED: 'actionConnected',
  DISCONNECT: 'actionDisconnect',
  DISCONNECTED: 'actionDisconnected',
  DROP_TYPES: ['__NATIVE_URL__'],
  NEW_IMAGE: 'actionNewImage',
  RESOLVE_IMAGE: 'actionResolveImage',
  SEND: 'actionSend',
  STORE_TOKEN: 'actionStoreToken',
  STORE_USERNAME: 'actionStoreUserName',
  STORE_USER: 'actionStoreUser',
  TOGGLE_SETTINGS: 'actionToggleSettings',
  UPDATE_VOLUME: 'actionUpdateVolume',
  UPDATE_PLAYBACK_STATE: 'actionPlaybackState',
  UPDATE_PROGRESS_TIMER: 'actionUpdateProgressTimer',
  UPDATE_RADIO_STREAM_STATE: 'updateRadioStreamState'
}
