# Backend API Deployment Configuration
service: jukebox-backend

# Name of the container image for backend
image: whomwah/kyan-jukebox-backend

# Deploy to these servers
servers:
  web:
    hosts:
      - 192.168.2.3
    proxy: false

# Credentials for your image host
registry:
  username: whomwah
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup for backend
builder:
  arch: arm64
  dockerfile: Dockerfile.backend
  context: .

# Enable proxy for backend (serves the api)
proxy:
  ssl: false
  app_port: 8080
  healthcheck:
    path: /up
    interval: 10
    timeout: 2

# Backend environment variables
env:
  clear:
    PORT: 8080
    NODE_ENV: production
    EXPLICIT_CONTENT: true
    SPOTIFY_NEW_TRACKS_ADDED_LIMIT: 10
  secret:
    - SPOTIFY_ID
    - SPOTIFY_SECRET
    - WS_MOPIDY_URL
    - WS_MOPIDY_PORT

# Use a different ssh user than root
ssh:
  user: ubuntu

# Use persistent storage volume
volumes:
  - "/db:/databases"

# Configure rolling deploys
boot:
  limit: 10
  wait: 2

# Aliases for backend management
aliases:
  shell: app exec --interactive --reuse "bash"
  logs: app logs --lines 100 --follow
