export default {
  GENERIC: 'message',
  MOPIDY: 'mopidy',
  SEARCH: 'search',
  VOTE: 'vote',
  INCOMING_CORE: 'INCOMING MOPIDY [CORE]',
  INCOMING_CLIENT: 'INCOMING CLIENT',
  INCOMING_MOPIDY: 'INCOMING MOPIDY',
  OUTGOING_ALL: 'OUTGOING BROADCAST',
  OUTGOING_STATE_CHANGE: 'OUTGOING STATE CHANGE',
  OUTGOING_API: 'OUTGOING API',
  OUTGOING_API_AUTH: 'OUTGOING API [AUTHED]',
  OUTGOING_MOPIDY: 'OUTGOING MOPIDY'
}
