export default {
  GENERIC: 'message',
  MOPIDY: 'mopidy',
  SEARCH: 'search',
  IMAGE: 'image',
  INCOMING_CORE: 'INCOMING MOPIDY [CORE]',
  INCOMING_CLIENT: 'INCOMING CLIENT',
  INCOMING_MOPIDY: 'INCOMING MOPIDY',
  OUTGOING_API_ALL: 'OUTGOING API BROADCAST',
  OUTGOING_API: 'OUTGOING API',
  OUTGOING_API_AUTH: 'OUTGOING API [AUTHED]',
  OUTGOING_MOPIDY: 'OUTGOING MOPIDY'
}
